=== senithkay/vscode-extensions-public/workspaces/mi/mi-extension/src/test/e2e-playwright-tests/data/datamapper-files/array/out.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "d1O": {
      "type": "array",
      "items": {
        "type": "number"
      }
    },
    "m1O": {
      "type": "array",
      "items": {
        "type": "number"
      }
    },
    "m1objO": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "q1": {
            "type": "string"
          },
          "q2": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "q1",
          "q2"
        ]
      }
    },
    "i1O": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "i2O": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "iobjO": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "p1": {
            "type": "string"
          },
          "p2": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "p1",
          "p2"
        ]
      }
    },
    "d2O": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {
          "type": "number"
        }
      }
    },
    "m2O": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {
          "type": "number"
        }
      }
    },
    "s10O": {
      "type": "string"
    },
    "s21O": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "required": [
    "d1O",
    "m1O",
    "m1objO",
    "i1O",
    "i2O",
    "iobjO",
    "d2O",
    "m2O",
    "s10O",
    "s21O"
  ]
}

=== senithkay/vscode-extensions-public/workspaces/mi/mi-extension/src/test/e2e-playwright-tests/data/datamapper-files/array/out.json
{
    "d1O": [10, 20, 30],
    "m1O": [40, 50, 60],
    "m1objO": [
      {
        "q1": "sampleQ1",
        "q2": ["string1", "string2"]
      },
      {
        "q1": "sampleQ2",
        "q2": ["string3", "string4"]
      }
    ],
    "i1O": ["stringA", "stringB", "stringC"],
    "i2O": [
      ["nestedString1", "nestedString2"],
      ["nestedString3", "nestedString4"]
    ],
    "iobjO": [
      {
        "p1": "exampleP1",
        "p2": ["arrayStr1", "arrayStr2"]
      },
      {
        "p1": "exampleP2",
        "p2": ["arrayStr3", "arrayStr4"]
      }
    ],
  
    "d2O": [
      [100, 200],
      [300, 400]
    ],
    "m2O": [
      [500, 600],
      [700, 800]
    ],
  
    "s10O": "singleOutputString",
    "s21O": ["outputStr1", "outputStr2", "outputStr3"]
}
